### ISSUE TITLE
Regarding the direction of the metal layer in the LEF file

### ISSUE THREAD

**Issue by pacificwind** [The-OpenROAD-Project/asap7#28]
Hi, in the 4x-scaled tech LEF file(asap7_tech_4x_201209.lef), I found that 
odd metal layers (M1, M3, M5, M7, and M9) have VERTICAL DIRECTION for their routing type and
even metal layers (M2, M4, M6, and M8) have HORIZONTAL DIRECTION for their routing type.

The conventional PDK such as TSMC 28nm usually use the opposite way.
In those PDKs, odd metal layers have HORIZONTAL DIRECTION and even metal layers have VERTICAL DIRECTION.

And I think ASAP7 also uses the conventional way because the M1 layer is used for VDD and VSS in the standard cell, so I think setting the direction of M1 layer as HORIZONTAL is natural.

Are the odd metal layers with VERTICAL DIRECTION and even metal layers with HORIZONTAL DIRECTION are intentionally set?
Or are those settings not important?

**Comment by snpagliarini** [comment]
I will add that M1 is vertical in a commercial finfet technology LEF I have taped out with.
And that M1 is horizontal in a commercial bulk technology LEF from the same foundry. 
The question is what is the meaning of "conventional".

**Comment by pacificwind** [comment]
Oh the meaning of "conventional" was commercial bulk technology. I think "commercial bulk technology" is much better way to convey meaning than "conventional". Thank you for letting me know. 

And thank you for sharing your knowledge! I am surprised that M1 is vertical in a commercial FINFET technology

**Comment by pacificwind** [comment]
Dear Professor Pagliarini,

I'd like to ask more about the FINFET technology.

As far as I know, commercial bulk technology uses "power ring" for the power interconnect.
But, the example script for the PnR (Placement and Route) in ASAP7 uses "power stripe' for the power interconnect.

Should we use power stripe instead of power ring for FINFET technology? Or it doesn't matter?

**Comment by pacificwind** [comment]
And I'd like to ask whether there is a specific reason why commercial finfet technology(M1 vertical) use the different orientation with the commercial bulk technology(M1 horizontal) if you know about it.

**Comment by snpagliarini** [comment]
"Should we use power stripe instead of power ring for FINFET technology?"
The answer often is you should use both. In modern SoC design, you have EM/IR drop issues that are hard to solve with a single power mesh on your metal Mtop and Mtop-1. It is now common to have the notion of two power grids, one on the lower metals and one on the upper metals. At the lower level, you will see M3 vertical stripes connecting to overlapping M1/M2 rails (stapled together with vias). This is what you might have seen in the ASAP7nm example Innovus script. But that by itself is not enough. You still need a ring around your block, say M6/M7. And you still need to take care of chip-level distribution of power, say in M8/M9.

There might be other reasons why things evolved this way due to litho/patterning constraints (M1 is very different from M5, for instance. not only in size, but also how they are deposited. LELE vs EUV vs SADP vs whatever-comes-next). I am not an expert in lithography, so I can't say much more.
